
on:
  workflow_dispatch:
  schedule:
    - cron: '12 12 * * *'

jobs:
  update-help-post-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up .Net
        uses: Elskom/build-dotnet@v1.1.1
      
      - name: Build bot
        run: dotnet publish
      
      - name: Create secrets files
        if: ${{ success() }}
        run: |
          mkdir -p ./publish/secrets
          echo "${{ secrets.GH_AUTH }}" > ./publish/secrets/github_auth
          echo "${{ secrets.BOT_TOKEN }}" > ./publish/secrets/bot_token

      - name: Give execute permission
        run: chmod u+x ./publish/help_channel_mirror

      - name: Start program and update data
        if: ${{ success() }}
        run: ./publish/help_channel_mirror -auto